using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RitoBot
{
    class Enums
    {

        public static int championToId(string name)
        {
            switch (name)
            {
                case "AATROX":
                    return 266;
                case "AHRI":
                    return 103;
                case "AKALI":
                    return 84;
                case "ALISTAR":
                    return 12;
                case "AMUMU":
                    return 32;
                case "ANIVIA":
                    return 34;
                case "ANNIE":
                    return 1;
                case "ASHE":
                    return 22;
                case "AZIR":
                    return 268;
                case "BLITZCRANK":
                    return 53;
                case "BRAND":
                    return 63;
                case "BRAUM":
                    return 201;
                case "CAITLYN":
                    return 51;
                case "CASSIOPEIA":
                    return 69;
                case "CHOGATH":
                    return 31;
                case "CORKI":
                    return 42;
                case "DARIUS":
                    return 122;
                case "DIANA":
                    return 131;
                case "MUNDO":
                    return 36;
                case "DRAVEN":
                    return 119;
                case "ELISE":
                    return 60;
                case "EVELYNN":
                    return 28;
                case "EZREAL":
                    return 81;
                case "FIDDLESTICKS":
                    return 9;
                case "FIORA":
                    return 114;
                case "FIZZ":
                    return 105;
                case "GALIO":
                    return 3;
                case "GANGPLANK":
                    return 41;
                case "GAREN":
                    return 86;
                case "GNAR":
                    return 150;
                case "GRAGAS":
                    return 79;
                case "GRAVES":
                    return 104;
                case "HECARIM":
                    return 120;
                case "HEIMERDIGER":
                    return 74;
                case "IRELIA":
                    return 39;
                case "JANNA":
                    return 40;
                case "JARVAN":
                    return 59;
                case "JAX":
                    return 24;
                case "JAYCE":
                    return 126;
                case "JINX":
                    return 222;
                case "KARMA":
                    return 43;
                case "KARTHUS":
                    return 30;
                case "KASSADIN":
                    return 38;
                case "KATARINA":
                    return 55;
                case "KAYLE":
                    return 10;
                case "KENNEN":
                    return 85;
                case "KHAZIX":
                    return 121;
                case "KOGMAW":
                    return 96;
                case "LEBLANC":
                    return 7;
                case "LEESIN":
                    return 64;
                case "LEONA":
                    return 89;
                case "LISSANDRA":
                    return 127;
                case "LUCIN":
                    return 236;
                case "LULU":
                    return 117;
                case "LUX":
                    return 99;
                case "MALPHITE":
                    return 54;
                case "MALZAHAR":
                    return 90;
                case "MAOKAI":
                    return 57;
                case "MASTERYI":
                    return 11;
                case "MISSFORTUNE":
                    return 21;
                case "MORDEKAISER":
                    return 82;
                case "MORGANA":
                    return 25;
                case "NAMI":
                    return 267;
                case "NASUS":
                    return 75;
                case "NAUTILUS":
                    return 111;
                case "NIDALEE":
                    return 76;
                case "NOCTURNE":
                    return 56;
                case "NUNU":
                    return 20;
                case "OLAF":
                    return 2;
                case "ORIANNA":
                    return 61;
                case "PANTHEON":
                    return 80;
                case "POPPY":
                    return 78;
                case "QUINN":
                    return 133;
                case "RAMMUS":
                    return 33;
                case "RENEKTON":
                    return 58;
                case "RENGAR":
                    return 107;
                case "RIVEN":
                    return 92;
                case "RUMBLE":
                    return 68;
                case "RYZE":
                    return 13;
                case "SEJUANI":
                    return 113;
                case "SHACO":
                    return 35;
                case "SHEN":
                    return 98;
                case "SHYVANA":
                    return 102;
                case "SINGED":
                    return 27;
                case "SION":
                    return 14;
                case "SIVIR":
                    return 15;
                case "SKARNER":
                    return 72;
                case "SONA":
                    return 37;
                case "SORAKA":
                    return 37;
                case "SWAIN":
                    return 50;
                case "SYNDRA":
                    return 134;
                case "TALON":
                    return 91;
                case "TARIC":
                    return 44;
                case "TEEMO":
                    return 17;
                case "THRESH":
                    return 412;
                case "TRISTANA":
                    return 18;
                case "TRUNDLE":
                    return 48;
                case "TRYNDAMERE":
                    return 23;
                case "TWISTEDFATE":
                    return 4;
                case "TWITCH":
                    return 29;
                case "UDYR":
                    return 77;
                case "URGOT":
                    return 6;
                case "VARUS":
                    return 110;
                case "VAYNE":
                    return 67;
                case "VEIGAR":
                    return 45;
                case "VELKOZ":
                    return 161;
                case "VI":
                    return 254;
                case "VIKTOR":
                    return 112;
                case "VLADIMIR":
                    return 8;
                case "VOLIBEAR":
                    return 106;
                case "WARWICK":
                    return 19;
                case "WUKONG":
                    return 62;
                case "XERATH":
                    return 101;
                case "XINZHAO":
                    return 5;
                case "YASUO":
                    return 157;
                case "YORICK":
                    return 83;
                case "ZAC":
                    return 154;
                case "ZED":
                    return 238;
                case "ZIGGS":
                    return 115;
                case "ZILEAN":
                    return 26;
                case "ZYRA":
                    return 143;
                default:
                    return 0;
            }
        }

        public static int spellToId(string name)
        {
            switch (name)
            {
                case "BARRIER":
                    return 21;
                case "CLAIRVOYANCE":
                    return 2;
                case "CLARITY":
                    return 13;
                case "CLEANSE":
                    return 1;
                case "EXHAUST":
                    return 3;
                case "FLASH":
                    return 4;
                case "GARRISON":
                    return 17;
                case "GHOST":
                    return 6;
                case "HEAL":
                    return 7;
                case "IGNITE":
                    return 14;
                case "REVIVE":
                    return 10;
                case "SMITE":
                    return 11;
                case "TELEPORT":
                    return 12;
                default:
                    return 0;
            }
        }
    }
}
